export const datos = [
  {
    name: "Carlos Pérez",
    career: "Ingeniería Informática",
    id: "001",
    state: "Aprobado",
    percentage: 88.5,
  },
  {
    name: "Laura Gómez",
    career: "Medicina",
    id: "002",
    state: "Aprobado",
    percentage: 92.3,
  },
  {
    name: "Juan Martínez",
    career: "Derecho",
    id: "003",
    state: "Retirado",
    percentage: 75.4,
  },
  {
    name: "Ana Sánchez",
    career: "Arquitectura",
    id: "004",
    state: "Proceso",
    percentage: 81.7,
  },
  {
    name: "Miguel Rodríguez",
    career: "Economía",
    id: "005",
    state: "Retirado",
    percentage: 79.6,
  },
  {
    name: "María Fernández",
    career: "Psicología",
    id: "006",
    state: "Aprobado",
    percentage: 85.2,
  },
  {
    name: "Pedro García",
    career: "Biología",
    id: "007",
    state: "Aprobado",
    percentage: 90.1,
  },
  {
    name: "Elena López",
    career: "Física",
    id: "008",
    state: "Proceso",
    percentage: 87.4,
  },
  {
    name: "Andrés Torres",
    career: "Química",
    id: "009",
    state: "Retirado",
    percentage: 76.8,
  },
  {
    name: "Lucía Herrera",
    career: "Matemáticas",
    id: "010",
    state: "Retirado",
    percentage: 5.0,
  },
  {
    name: "Sofía Ramírez",
    career: "Ingeniería Informática",
    id: "011",
    state: "Aprobado",
    percentage: 95.2,
  },
  {
    name: "David López",
    career: "Medicina",
    id: "012",
    state: "Proceso",
    percentage: 78.4,
  },
  {
    name: "Martín González",
    career: "Derecho",
    id: "013",
    state: "Aprobado",
    percentage: 83.7,
  },
  {
    name: "Julia Torres",
    career: "Arquitectura",
    id: "014",
    state: "Retirado",
    percentage: 65.9,
  },
  {
    name: "Daniela Cruz",
    career: "Economía",
    id: "015",
    state: "Aprobado",
    percentage: 88.1,
  },
  {
    name: "Gabriel Navarro",
    career: "Psicología",
    id: "016",
    state: "Retirado",
    percentage: 47.3,
  },
  {
    name: "Isabel Morales",
    career: "Biología",
    id: "017",
    state: "Proceso",
    percentage: 71.5,
  },
  {
    name: "Fernando Ruiz",
    career: "Física",
    id: "018",
    state: "Aprobado",
    percentage: 89.6,
  },
  {
    name: "Patricia Silva",
    career: "Química",
    id: "019",
    state: "Aprobado",
    percentage: 93.2,
  },
  {
    name: "Rafael Torres",
    career: "Matemáticas",
    id: "020",
    state: "Proceso",
    percentage: 77.8,
  },
  {
    name: "Victoria Mendoza",
    career: "Ingeniería Informática",
    id: "021",
    state: "Retirado",
    percentage: 62.4,
  },
  {
    name: "Luis Herrera",
    career: "Medicina",
    id: "022",
    state: "Aprobado",
    percentage: 91.7,
  },
  {
    name: "Teresa Fernández",
    career: "Derecho",
    id: "023",
    state: "Proceso",
    percentage: 84.0,
  },
  {
    name: "Ricardo Gómez",
    career: "Arquitectura",
    id: "024",
    state: "Retirado",
    percentage: 59.3,
  },
  {
    name: "Andrea Castro",
    career: "Economía",
    id: "025",
    state: "Aprobado",
    percentage: 94.5,
  },
  {
    name: "Paula Ortiz",
    career: "Psicología",
    id: "026",
    state: "Proceso",
    percentage: 80.2,
  },
  {
    name: "Juan Rojas",
    career: "Biología",
    id: "027",
    state: "Retirado",
    percentage: 45.8,
  },
  {
    name: "Carla Díaz",
    career: "Física",
    id: "028",
    state: "Aprobado",
    percentage: 87.0,
  },
  {
    name: "Miguel Castro",
    career: "Química",
    id: "029",
    state: "Proceso",
    percentage: 76.9,
  },
  {
    name: "Mariana Álvarez",
    career: "Matemáticas",
    id: "030",
    state: "Retirado",
    percentage: 53.6,
  },
  {
    name: "José Ramos",
    career: "Ingeniería Informática",
    id: "031",
    state: "Aprobado",
    percentage: 90.8,
  },
  {
    name: "Natalia Pérez",
    career: "Medicina",
    id: "032",
    state: "Retirado",
    percentage: 64.7,
  },
  {
    name: "Diego Vargas",
    career: "Derecho",
    id: "033",
    state: "Proceso",
    percentage: 79.9,
  },
  {
    name: "Laura Morales",
    career: "Arquitectura",
    id: "034",
    state: "Aprobado",
    percentage: 88.6,
  },
  {
    name: "Esteban Ruiz",
    career: "Economía",
    id: "035",
    state: "Retirado",
    percentage: 54.3,
  },
  {
    name: "Claudia Mendoza",
    career: "Psicología",
    id: "036",
    state: "Proceso",
    percentage: 73.2,
  },
  {
    name: "Alberto Fernández",
    career: "Biología",
    id: "037",
    state: "Aprobado",
    percentage: 92.9,
  },
  {
    name: "Lucía Gutiérrez",
    career: "Física",
    id: "038",
    state: "Retirado",
    percentage: 60.1,
  },
  {
    name: "Mario Delgado",
    career: "Química",
    id: "039",
    state: "Aprobado",
    percentage: 89.4,
  },
  {
    name: "Emma Sosa",
    career: "Matemáticas",
    id: "040",
    state: "Proceso",
    percentage: 70.0,
  },
  {
    name: "Juanita López",
    career: "Ingeniería Informática",
    id: "041",
    state: "Aprobado",
    percentage: 93.5,
  },
  {
    name: "Carlos Sánchez",
    career: "Medicina",
    id: "042",
    state: "Proceso",
    percentage: 84.5,
  },
  {
    name: "Patricia Herrera",
    career: "Derecho",
    id: "043",
    state: "Retirado",
    percentage: 51.7,
  },
  {
    name: "Roberto Pérez",
    career: "Arquitectura",
    id: "044",
    state: "Aprobado",
    percentage: 91.2,
  },
  {
    name: "Alejandra Torres",
    career: "Economía",
    id: "045",
    state: "Proceso",
    percentage: 82.3,
  },
  {
    name: "Valeria Silva",
    career: "Psicología",
    id: "046",
    state: "Aprobado",
    percentage: 94.0,
  },
  {
    name: "Ignacio Morales",
    career: "Biología",
    id: "047",
    state: "Retirado",
    percentage: 48.6,
  },
  {
    name: "Clara Ortega",
    career: "Física",
    id: "048",
    state: "Proceso",
    percentage: 75.4,
  },
];
